image: instrumentisto/rsync-ssh

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

test:
  stage: test
  script:
  - mkdir test
  - rsync -av --progress . ./test --exclude test
  artifacts:
    paths:
    - test
  except:
  - master

pages:
  stage: deploy
  script:
  - mkdir public
  - rsync -av --progress . ./public --exclude public
  artifacts:
    paths:
    - public
  only:
  - master
