image: ruby:2.3

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8

before_script:
  - apt install rsync

test:
  stage: test
  script:
  - mkdir test
  artifacts:
    paths:
    - .
  except:
  - master

pages:
  stage: deploy
  script:
  - mkdir public
  artifacts:
    paths:
    - .
  only:
  - master
